version: "3"

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_DB=apisolid
      - POSTGRES_PASSWORD=docker
